language: node_js
node_js:
- 10

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: ethdocs/ethdocs.github.io
    - GIT_SOURCE: _docpress

script:
- npm install docpress && ./node_modules/.bin/docpress build

after_success:
- chmod +x build.sh && ./build.sh